import frappe
import json
import requests
from datetime import datetime

@frappe.whitelist(allow_guest=True)
def get_debit_note():

    doc_list = frappe.get_all('Purchase Invoice', filters={'docstatus': 1, "update_stock":0, 'is_return': 1}, fields=['*'])
    list_of_purchases= []
    for doc in doc_list:
        supplier = frappe.get_doc("Supplier", doc.supplier)
        supplier_add = frappe.get_doc("Address",supplier.supplier_primary_address)
        list_of_purchases.append(purchase_invoice_json(get_tagged_accounts_amount(doc.name), supplier, supplier_add, doc))
    return list_of_purchases

def get_tagged_accounts_amount(purchase_invoice_name):

    purchase_invoice = frappe.get_doc("Purchase Invoice", purchase_invoice_name)
    account_amount = {}
    gl_entries = frappe.get_all("GL Entry", filters={"voucher_type": "Purchase Invoice", "voucher_no": purchase_invoice_name}, fields=["*"], order_by="creation asc")

    for entry in gl_entries:
        account = entry.account

        normalized_account = account
        if 'Input Tax' in account:
            normalized_account = 'Input Tax' 
        
        if entry.debit is not None and entry.debit > 0:
            if normalized_account in account_amount:
                account_amount[normalized_account]['debit'] += entry.debit
            else:
                account_amount[normalized_account] = {'debit': entry.debit, 'credit': 0}

        elif entry.credit is not None and entry.credit > 0:
            if normalized_account in account_amount:
                account_amount[normalized_account]['credit'] += entry.credit
            else:
                account_amount[normalized_account] = {'debit': 0, 'credit': entry.credit}

    for account, amounts in account_amount.items():
        if amounts['debit'] > 0 and amounts['credit'] > 0:
            amounts['credit'] = abs(amounts['debit'] - amounts['credit'])
            amounts['debit'] = 0


    def custom_sort_key(account):
        if 'creditors' in account.lower():
            return 1
        elif 'write off' in account.lower():
            return 2
        elif 'tax' in account.lower():
            return 3
        elif 'round off' in account.lower():
            return 5
        else:
            return 4

  
    sorted_account_amount = dict(sorted(account_amount.items(), key=lambda item: custom_sort_key(item[0])))
   
    return (sorted_account_amount)

def purchase_invoice_json(tagged_acc, supplier, supplier_add, doc):

    document = frappe.get_doc("Purchase Invoice", doc.name)
    company = frappe.get_doc("Company", doc.company)
    company_address_billing = frappe.get_doc("Address", get_company_address(doc.company)[0]) if document.billing_address else ""
    # company_address_shipping = frappe.get_doc("Address", get_company_address(doc.company)[0]) if document.shipping_address else ""
    cost_center = frappe.get_doc("Cost Center", doc.cost_center) if document.cost_center else ""
    gst_category = {
        "Unregistered": "Unregistered/Consumer",
        "Registered Regular": "Regular",
        "Registered Composition": "Composition",
        "SEZ": "Regular - SEZ"
    }.get(supplier.gst_category, supplier.gst_category)

    gst_category_company = {
        "Unregistered": "Unregistered/Consumer",
        "Registered Regular": "Regular",
        "Registered Composition": "Composition",
        "SEZ": "Regular - SEZ"
    }.get(company.gst_category, company.gst_category)

    # gst_category_shipping = {
    #     "Unregistered": "Unregistered/Consumer",
    #     "Registered Regular": "Regular",
    #     "Registered Composition": "Composition",
    #     "SEZ": "Regular - SEZ"
    # }.get(company_address_shipping.gst_category, company_address_shipping.gst_category)

    company_idx = (frappe.db.sql(f"select idx from `tabTS Tally Company` where company_name ='{doc.company}'", as_dict=True))[0]['idx']

    list_of_purchase_invoices = []
    
    for key, value in tagged_acc.items():
        if value['debit'] > 0:
            if "Creditors" in key:
                doc_json = {
                        "Autoid": "",
                        "CompanyNumber": str(company_idx),
                        "TallyMasterid": 1,
                        "Voucherid": document.name,
                        "VoucherNumber": document.name,
                        "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherType": "Debit Note",
                        "VoucherTypeParent": "Debit Note",
                        "LedgerName": supplier.supplier_name,
                        "LedgerParent": "Sundry Creditors",
                        "LedgerAddress": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "LedgerState": supplier_add.state if supplier_add.state else "",
                        "LedgerCountry": supplier_add.country if supplier_add.country else "",
                        "LedgerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        "LedgerMobile": supplier.mobile_no if supplier.mobile_no else "",
                        "LedgerGstReg": gst_category if gst_category else "",
                        "LedgerPan": supplier.pan if supplier.pan else "",
                        "LedgerGstin": supplier.gstin if supplier.gstin else "",
                        "BillName": "",
                        "BillDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "CrDr":"Dr",
                        "CostCategory": "",
                        "CostCentre": (cost_center.company) if cost_center else "",
                        "Stockitem": "",
                        "Godown": "",
                        "BatchNo": "",
                        "Quantity": "",
                        "Rate": "",
                        "Discount": "",
                        "Amount": str(value['debit']),
                        "OrderNo": "",
                        "OrderDate": "",
                        "TrackingNo": "",
                        "TrackingDate": "",
                        "TermsOfPayment": "",
                        "OtherRef": "",
                        "TermsOfDelivery1": "",
                        "TermsOfDelivery2": "",
                        "DispatchDocNo": "",
                        "ReceiptDocNo": "",
                        "DispatchedThrough": "",
                        "Destination": "",
                        "CarrierName": "",
                        "BillOfLanding": "",
                        "BillOfLandingDate": "",
                        "VehicleNo": "",
                        "BuyerName": supplier.supplier_name,
                        "BuyerMailingName": supplier.supplier_name,
                        "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                        "BuyerState": supplier_add.state if supplier_add.state else "",
                        "BuyerCountry": supplier_add.country if supplier_add.country else "",
                        "BuyerGstReg": gst_category if gst_category else "",
                        "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                        "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        "ConsigneeName": supplier.supplier_name,
                        "ConsigneeMailingName": supplier.supplier_name,
                        "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                        "ConsigneeState": supplier_add.state if supplier_add.state else "",
                        "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                        "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                        "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                        "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                        "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                        "CmpGstin": company.gstin if company.gstin else "",
                        "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                        "GstOvrdnTaxability":"",
                        "GstOvrdnTypeofsupply":"",
                        "GstHsnName":"",
                        "GstHsnDescription":"",
                        "CgstGstRateDutyhead":"",
                        "CgstGstRateValuationtype":"",
                        "CgstGstRate":"",
                        "SgstGstRateDutyhead":"",
                        "SgstGstRateValuationtype":"",
                        "SgstGstRate":"",
                        "IgstGstRateDutyhead":"",
                        "IgstGstRateValuationtype":"",
                        "IgstGstRate":"",
                        "Reference": document.bill_no if document.bill_no else "",
                        "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                        "VoucherSourceGodown": "",				
                        "Narration": (document.remarks).replace("\n",". ") if document.remarks else "",
                    }
                list_of_purchase_invoices.append(doc_json)
            
            elif "Cost of Goods Sold" in key:
                pass
            
            else:
                parrent_acc = frappe.get_doc("Account", key)
                doc_json = {
                        "Autoid": "",
                        "CompanyNumber": str(company_idx),
                        "TallyMasterid": 1,
                        "Voucherid": document.name,
                        "VoucherNumber": document.name,
                        "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherType": "Debit Note",
                        "VoucherTypeParent": "Debit Note",
                        "LedgerName": "Roundoff"  if "Rounded Off" in key else (key).split(" - ")[0],
                        "LedgerParent": (parrent_acc.parent_account).split(" - ")[0] if parrent_acc.parent_account else "",
                        "LedgerAddress":"",
                        "LedgerState": "",
                        "LedgerCountry": "",
                        "LedgerPincode": "",
                        "LedgerMobile": "",
                        "LedgerGstReg": "",
                        "LedgerPan": "",
                        "LedgerGstin": "",
                        "BillName": "",
                        "BillDate": "",
                        "CrDr":"Dr",
                        "CostCategory": "",
                        "CostCentre": (cost_center.company) if cost_center else "",
                        "Stockitem": "",
                        "Godown": "",
                        "BatchNo": "",
                        "Quantity": "",
                        "Rate": "",
                        "Discount": "",
                        "Amount": str(value['debit']),
                        "OrderNo": "",
                        "OrderDate": "",
                        "TrackingNo": "",
                        "TrackingDate": "",
                        "TermsOfPayment": "",
                        "OtherRef": "",
                        "TermsOfDelivery1": "",
                        "TermsOfDelivery2": "",
                        "DispatchDocNo": "",
                        "ReceiptDocNo": "",
                        "DispatchedThrough": "",
                        "Destination": "",
                        "CarrierName": "",
                        "BillOfLanding": "",
                        "BillOfLandingDate": "",
                        "VehicleNo": "",
                    # Commented for future need
                        # "BuyerName": supplier.supplier_name,
                        # "BuyerMailingName": supplier.supplier_name,
                        # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                        # "BuyerState": supplier_add.state if supplier_add.state else "",
                        # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                        # "BuyerGstReg": gst_category if gst_category else "",
                        # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                        # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        # "ConsigneeName": supplier.supplier_name,
                        # "ConsigneeMailingName": supplier.supplier_name,
                        # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                        # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                        # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                        # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                        # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                        # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                    # Commented for future need
                        "BuyerName": "",
                        "BuyerMailingName": "",
                        "BuyerAddress1": "",
                        "BuyerAddress2": "",
                        "BuyerState": "",
                        "BuyerCountry": "",
                        "BuyerGstReg": "",
                        "BuyerGSTIN": "",
                        "BuyerPincode": "",
                        "ConsigneeName": "",
                        "ConsigneeMailingName": "",
                        "ConsigneeAddress1": "",
                        "ConsigneeAddress2": "",
                        "ConsigneeState": "",
                        "ConsigneeCountry": "",
                        "ConsigneeGSTIN": "",
                        "ConsigneePincode": "",
                        "PlaceOfSupply": "",
                        "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                        "CmpGstin": company.gstin if company.gstin else "",
                        "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                        "GstOvrdnTaxability":"",
                        "GstOvrdnTypeofsupply":"",
                        "GstHsnName":"",
                        "GstHsnDescription":"",
                        "CgstGstRateDutyhead":"",
                        "CgstGstRateValuationtype":"",
                        "CgstGstRate":"",
                        "SgstGstRateDutyhead":"",
                        "SgstGstRateValuationtype":"",
                        "SgstGstRate":"",
                        "IgstGstRateDutyhead":"",
                        "IgstGstRateValuationtype":"",
                        "IgstGstRate":"",
                        "Reference": document.bill_no if document.bill_no else "",
                        "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                        "VoucherSourceGodown": "",				
                        "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                    }
                list_of_purchase_invoices.append(doc_json)

        elif value['credit'] > 0:
            if 'Creditors' in key:
                doc_json = {
                        "Autoid": "",
                        "CompanyNumber": str(company_idx),
                        "TallyMasterid": 1,
                        "Voucherid": document.name,
                        "VoucherNumber": document.name,
                        "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherType": "Debit Note",
                        "VoucherTypeParent": "Debit Note",
                        "LedgerName": supplier.supplier_name,
                        "LedgerParent": "Sundry Creditors",
                        "LedgerAddress": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "LedgerState": supplier_add.state if supplier_add.state else "",
                        "LedgerCountry": supplier_add.country if supplier_add.country else "",
                        "LedgerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        "LedgerMobile": supplier.mobile_no if supplier.mobile_no else "",
                        "LedgerGstReg": gst_category if gst_category else "",
                        "LedgerPan": supplier.pan if supplier.pan else "",
                        "LedgerGstin": supplier.gstin if supplier.gstin else "",
                        "BillName": "",
                        "BillDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "CrDr":"Cr",
                        "CostCategory": "",
                        "CostCentre": (cost_center.company) if cost_center else "",
                        "Stockitem": "",
                        "Godown": "",
                        "BatchNo": "",
                        "Quantity": "",
                        "Rate": "",
                        "Discount": "",
                        "Amount": str(value['credit']),
                        "OrderNo": "",
                        "OrderDate": "",
                        "TrackingNo": "",
                        "TrackingDate": "",
                        "TermsOfPayment": "",
                        "OtherRef": "",
                        "TermsOfDelivery1": "",
                        "TermsOfDelivery2": "",
                        "DispatchDocNo": "",
                        "ReceiptDocNo": "",
                        "DispatchedThrough": "",
                        "Destination": "",
                        "CarrierName": "",
                        "BillOfLanding": "",
                        "BillOfLandingDate": "",
                        "VehicleNo": "",
                        "BuyerName": supplier.supplier_name,
                        "BuyerMailingName": supplier.supplier_name,
                        "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                        "BuyerState": supplier_add.state if supplier_add.state else "",
                        "BuyerCountry": supplier_add.country if supplier_add.country else "",
                        "BuyerGstReg": gst_category if gst_category else "",
                        "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                        "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        "ConsigneeName": supplier.supplier_name,
                        "ConsigneeMailingName": supplier.supplier_name,
                        "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                        "ConsigneeState": supplier_add.state if supplier_add.state else "",
                        "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                        "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                        "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                        "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                        "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                        "CmpGstin": company.gstin if company.gstin else "",
                        "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                        "GstOvrdnTaxability":"",
                        "GstOvrdnTypeofsupply":"",
                        "GstHsnName":"",
                        "GstHsnDescription":"",
                        "CgstGstRateDutyhead":"",
                        "CgstGstRateValuationtype":"",
                        "CgstGstRate":"",
                        "SgstGstRateDutyhead":"",
                        "SgstGstRateValuationtype":"",
                        "SgstGstRate":"",
                        "IgstGstRateDutyhead":"",
                        "IgstGstRateValuationtype":"",
                        "IgstGstRate":"",
                        "Reference": document.bill_no if document.bill_no else "",
                        "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                        "VoucherSourceGodown": "",				
                        "Narration": (document.remarks).replace("\n",". ") if document.remarks else "",
                    }
                list_of_purchase_invoices.append(doc_json)
            
            elif "Input Tax" in key:
                
                items_tax = frappe.db.sql(f"""
                                SELECT 
                                    parent,
                                    cgst_rate, 
                                    sgst_rate, 
                                    igst_rate, 
                                    SUM(cgst_amount) AS cgst_amount, 
                                    SUM(sgst_amount) AS sgst_amount, 
                                    SUM(igst_amount) AS igst_amount 
                                FROM `tabPurchase Invoice Item` 
                                WHERE parent='{doc.name}' AND docstatus=1
                                GROUP BY parent, cgst_rate, sgst_rate, igst_rate
                            """, as_dict=True)

                for item_tax in items_tax:
                    if item_tax['igst_rate']>0 and item_tax['cgst_rate']==0 and item_tax['sgst_rate']==0:
                        doc_json_igst ={
                            "Autoid": "",
                            "CompanyNumber": str(company_idx),
                            "TallyMasterid": 1,
                            "Voucherid": document.name,
                            "VoucherNumber": document.name,
                            "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherType": "Debit Note",
                            "VoucherTypeParent": "Debit Note",
                            "LedgerName": "Input Tax IGST @ "+str(item_tax['igst_rate'])+"%",
                            "LedgerParent": "Duties & Taxes",
                            "LedgerAddress":"",
                            "LedgerState": "",
                            "LedgerCountry": "",
                            "LedgerPincode": "",
                            "LedgerMobile": "",
                            "LedgerGstReg": "",
                            "LedgerPan": "",
                            "LedgerGstin": "",
                            "BillName": "",
                            "BillDate": "",
                            "CrDr": "Cr",
                            "CostCategory": "",
                            "CostCentre": (cost_center.company) if cost_center else "",
                            "Stockitem": "",
                            "Godown": "",
                            "BatchNo": "",
                            "Quantity": "",
                            "Rate": "",
                            "Discount": "",
                            "Amount": str(abs(item_tax['igst_amount'])),
                            "OrderNo": "",
                            "OrderDate": "",
                            "TrackingNo": "",
                            "TrackingDate": "",
                            "TermsOfPayment": "",
                            "OtherRef": "",
                            "TermsOfDelivery1": "",
                            "TermsOfDelivery2": "",
                            "DispatchDocNo": "",
                            "ReceiptDocNo": "",
                            "DispatchedThrough": "",
                            "Destination": "",
                            "CarrierName": "",
                            "BillOfLanding": "",
                            "BillOfLandingDate": "",
                            "VehicleNo": "",
                        # Commented for future need
                            # "BuyerName": supplier.supplier_name,
                            # "BuyerMailingName": supplier.supplier_name,
                            # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                            # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                            # "BuyerState": supplier_add.state if supplier_add.state else "",
                            # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                            # "BuyerGstReg": gst_category if gst_category else "",
                            # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                            # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                            # "ConsigneeName": supplier.supplier_name,
                            # "ConsigneeMailingName": supplier.supplier_name,
                            # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                            # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                            # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                            # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                            # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                            # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                            # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                        # Commented for future need
                            "BuyerName": "",
                            "BuyerMailingName": "",
                            "BuyerAddress1": "",
                            "BuyerAddress2": "",
                            "BuyerState": "",
                            "BuyerCountry": "",
                            "BuyerGstReg": "",
                            "BuyerGSTIN": "",
                            "BuyerPincode": "",
                            "ConsigneeName": "",
                            "ConsigneeMailingName": "",
                            "ConsigneeAddress1": "",
                            "ConsigneeAddress2": "",
                            "ConsigneeState": "",
                            "ConsigneeCountry": "",
                            "ConsigneeGSTIN": "",
                            "ConsigneePincode": "",
                            "PlaceOfSupply": "",
                            "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                            "CmpGstin": company.gstin if company.gstin else "",
                            "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                            "GstOvrdnTaxability":"",
                            "GstOvrdnTypeofsupply":"",
                            "GstHsnName":"",
                            "GstHsnDescription":"",
                            "CgstGstRateDutyhead":"",
                            "CgstGstRateValuationtype":"",
                            "CgstGstRate":"",
                            "SgstGstRateDutyhead":"",
                            "SgstGstRateValuationtype":"",
                            "SgstGstRate":"",
                            "IgstGstRateDutyhead":"",
                            "IgstGstRateValuationtype":"",
                            "IgstGstRate":"",
                            "Reference": document.bill_no if document.bill_no else "",
                            "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                            "VoucherSourceGodown": "",				
                            "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                        }
                        list_of_purchase_invoices.append(doc_json_igst)
                    elif item_tax['igst_rate']==0 and item_tax['cgst_rate']>0 and item_tax['sgst_rate']>0:
                        doc_json_cgst ={
                            "Autoid": "",
                            "CompanyNumber": str(company_idx),
                            "TallyMasterid": 1,
                            "Voucherid": document.name,
                            "VoucherNumber": document.name,
                            "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherType": "Debit Note",
                            "VoucherTypeParent": "Debit Note",
                            "LedgerName": "Input Tax CGST @ "+str(item_tax['cgst_rate'])+"%",
                            "LedgerParent": "Duties & Taxes",
                            "LedgerAddress":"",
                            "LedgerState": "",
                            "LedgerCountry": "",
                            "LedgerPincode": "",
                            "LedgerMobile": "",
                            "LedgerGstReg": "",
                            "LedgerPan": "",
                            "LedgerGstin": "",
                            "BillName": "",
                            "BillDate": "",
                            "CrDr": "Cr",
                            "CostCategory": "",
                            "CostCentre": (cost_center.company) if cost_center else "",
                            "Stockitem": "",
                            "Godown": "",
                            "BatchNo": "",
                            "Quantity": "",
                            "Rate": "",
                            "Discount": "",
                            "Amount": str(abs(item_tax['cgst_amount'])),
                            "OrderNo": "",
                            "OrderDate": "",
                            "TrackingNo": "",
                            "TrackingDate": "",
                            "TermsOfPayment": "",
                            "OtherRef": "",
                            "TermsOfDelivery1": "",
                            "TermsOfDelivery2": "",
                            "DispatchDocNo": "",
                            "ReceiptDocNo": "",
                            "DispatchedThrough": "",
                            "Destination": "",
                            "CarrierName": "",
                            "BillOfLanding": "",
                            "BillOfLandingDate": "",
                            "VehicleNo": "",
                        # Commented for future need
                            # "BuyerName": supplier.supplier_name,
                            # "BuyerMailingName": supplier.supplier_name,
                            # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                            # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                            # "BuyerState": supplier_add.state if supplier_add.state else "",
                            # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                            # "BuyerGstReg": gst_category if gst_category else "",
                            # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                            # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                            # "ConsigneeName": supplier.supplier_name,
                            # "ConsigneeMailingName": supplier.supplier_name,
                            # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                            # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                            # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                            # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                            # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                            # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                            # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                        # Commented for future need
                            "BuyerName": "",
                            "BuyerMailingName": "",
                            "BuyerAddress1": "",
                            "BuyerAddress2": "",
                            "BuyerState": "",
                            "BuyerCountry": "",
                            "BuyerGstReg": "",
                            "BuyerGSTIN": "",
                            "BuyerPincode": "",
                            "ConsigneeName": "",
                            "ConsigneeMailingName": "",
                            "ConsigneeAddress1": "",
                            "ConsigneeAddress2": "",
                            "ConsigneeState": "",
                            "ConsigneeCountry": "",
                            "ConsigneeGSTIN": "",
                            "ConsigneePincode": "",
                            "PlaceOfSupply": "",
                            "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                            "CmpGstin": company.gstin if company.gstin else "",
                            "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                            "GstOvrdnTaxability":"",
                            "GstOvrdnTypeofsupply":"",
                            "GstHsnName":"",
                            "GstHsnDescription":"",
                            "CgstGstRateDutyhead":"",
                            "CgstGstRateValuationtype":"",
                            "CgstGstRate":"",
                            "SgstGstRateDutyhead":"",
                            "SgstGstRateValuationtype":"",
                            "SgstGstRate":"",
                            "IgstGstRateDutyhead":"",
                            "IgstGstRateValuationtype":"",
                            "IgstGstRate":"",
                            "Reference": document.bill_no if document.bill_no else "",
                            "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                            "VoucherSourceGodown": "",				
                            "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                        }
                        list_of_purchase_invoices.append(doc_json_cgst)
                        doc_json_sgst ={
                            "Autoid": "",
                            "CompanyNumber": str(company_idx),
                            "TallyMasterid": 1,
                            "Voucherid": document.name,
                            "VoucherNumber": document.name,
                            "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherType": "Debit Note",
                            "VoucherTypeParent": "Debit Note",
                            "LedgerName": "Input Tax SGST @ "+str(item_tax['sgst_rate'])+"%",
                            "LedgerParent": "Duties & Taxes",
                            "LedgerAddress":"",
                            "LedgerState": "",
                            "LedgerCountry": "",
                            "LedgerPincode": "",
                            "LedgerMobile": "",
                            "LedgerGstReg": "",
                            "LedgerPan": "",
                            "LedgerGstin": "",
                            "BillName": "",
                            "BillDate": "",
                            "CrDr": "Cr",
                            "CostCategory": "",
                            "CostCentre": (cost_center.company) if cost_center else "",
                            "Stockitem": "",
                            "Godown": "",
                            "BatchNo": "",
                            "Quantity": "",
                            "Rate": "",
                            "Discount": "",
                            "Amount": str(abs(item_tax['sgst_amount'])),
                            "OrderNo": "",
                            "OrderDate": "",
                            "TrackingNo": "",
                            "TrackingDate": "",
                            "TermsOfPayment": "",
                            "OtherRef": "",
                            "TermsOfDelivery1": "",
                            "TermsOfDelivery2": "",
                            "DispatchDocNo": "",
                            "ReceiptDocNo": "",
                            "DispatchedThrough": "",
                            "Destination": "",
                            "CarrierName": "",
                            "BillOfLanding": "",
                            "BillOfLandingDate": "",
                            "VehicleNo": "",
                        # Commented for future need
                            # "BuyerName": supplier.supplier_name,
                            # "BuyerMailingName": supplier.supplier_name,
                            # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                            # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                            # "BuyerState": supplier_add.state if supplier_add.state else "",
                            # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                            # "BuyerGstReg": gst_category if gst_category else "",
                            # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                            # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                            # "ConsigneeName": supplier.supplier_name,
                            # "ConsigneeMailingName": supplier.supplier_name,
                            # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                            # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                            # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                            # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                            # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                            # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                            # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                        # Commented for future need
                            "BuyerName": "",
                            "BuyerMailingName": "",
                            "BuyerAddress1": "",
                            "BuyerAddress2": "",
                            "BuyerState": "",
                            "BuyerCountry": "",
                            "BuyerGstReg": "",
                            "BuyerGSTIN": "",
                            "BuyerPincode": "",
                            "ConsigneeName": "",
                            "ConsigneeMailingName": "",
                            "ConsigneeAddress1": "",
                            "ConsigneeAddress2": "",
                            "ConsigneeState": "",
                            "ConsigneeCountry": "",
                            "ConsigneeGSTIN": "",
                            "ConsigneePincode": "",
                            "PlaceOfSupply": "",
                            "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                            "CmpGstin": company.gstin if company.gstin else "",
                            "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                            "GstOvrdnTaxability":"",
                            "GstOvrdnTypeofsupply":"",
                            "GstHsnName":"",
                            "GstHsnDescription":"",
                            "CgstGstRateDutyhead":"",
                            "CgstGstRateValuationtype":"",
                            "CgstGstRate":"",
                            "SgstGstRateDutyhead":"",
                            "SgstGstRateValuationtype":"",
                            "SgstGstRate":"",
                            "IgstGstRateDutyhead":"",
                            "IgstGstRateValuationtype":"",
                            "IgstGstRate":"",
                            "Reference": document.bill_no if document.bill_no else "",
                            "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                            "VoucherSourceGodown": "",				
                            "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                        }
                        list_of_purchase_invoices.append(doc_json_sgst)

            elif "Stock Received But Not Billed" in key or "Cost of Goods Sold" in key:
                parrent_acc = frappe.get_doc("Account", key)
                for row in document.items:
                    if key == row.expense_account:
                        if 'Input GST Out-state' in document.taxes_and_charges:
                            doc_json ={
                                "Autoid": "",
                                "CompanyNumber": str(company_idx),
                                "TallyMasterid": 1,
                                "Voucherid": document.name,
                                "VoucherNumber": document.name,
                                "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                                "VoucherType": "Debit Note",
                                "VoucherTypeParent": "Debit Note",
                                "LedgerName": row.item_name.upper() +" PURCHASE" if row.item_name else "PURCHASE",
                                "LedgerParent": "Purchase Accounts",
                                "LedgerAddress":"",
                                "LedgerState": "",
                                "LedgerCountry": "",
                                "LedgerPincode": "",
                                "LedgerMobile": "",
                                "LedgerGstReg": "",
                                "LedgerPan": "",
                                "LedgerGstin": "",
                                "BillName": "",
                                "BillDate": "",
                                "CrDr": "Cr",
                                "CostCategory": "",
                                "CostCentre": (cost_center.company) if cost_center else "",
                                "Stockitem": "",
                                "Godown": "",
                                "BatchNo": "",
                                "Quantity": "",
                                "Rate": "",
                                "Discount": "",
                                "Amount": str(abs(row.net_amount)) if row.net_amount else "",
                                "OrderNo": "",
                                "OrderDate": "",
                                "TrackingNo": "",
                                "TrackingDate": "",
                                "TermsOfPayment": "",
                                "OtherRef": "",
                                "TermsOfDelivery1": "",
                                "TermsOfDelivery2": "",
                                "DispatchDocNo": "",
                                "ReceiptDocNo": "",
                                "DispatchedThrough": "",
                                "Destination": "",
                                "CarrierName": "",
                                "BillOfLanding": "",
                                "BillOfLandingDate": "",
                                "VehicleNo": "",
                            # Commented for future need
                                # "BuyerName": supplier.supplier_name,
                                # "BuyerMailingName": supplier.supplier_name,
                                # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                                # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                                # "BuyerState": supplier_add.state if supplier_add.state else "",
                                # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                                # "BuyerGstReg": gst_category if gst_category else "",
                                # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                                # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                                # "ConsigneeName": supplier.supplier_name,
                                # "ConsigneeMailingName": supplier.supplier_name,
                                # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                                # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                                # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                                # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                                # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                                # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                                # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                            # Commented for future need
                                "BuyerName": "",
                                "BuyerMailingName": "",
                                "BuyerAddress1": "",
                                "BuyerAddress2": "",
                                "BuyerState": "",
                                "BuyerCountry": "",
                                "BuyerGstReg": "",
                                "BuyerGSTIN": "",
                                "BuyerPincode": "",
                                "ConsigneeName": "",
                                "ConsigneeMailingName": "",
                                "ConsigneeAddress1": "",
                                "ConsigneeAddress2": "",
                                "ConsigneeState": "",
                                "ConsigneeCountry": "",
                                "ConsigneeGSTIN": "",
                                "ConsigneePincode": "",
                                "PlaceOfSupply": "",
                                "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                                "CmpGstin": company.gstin if company.gstin else "",
                                "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                                "GstOvrdnTaxability": "Exempt" if row.gst_treatment == "Exempted" or row.gst_treatment == "Non-GST" or row.gst_treatment == "Nil-Rated" else row.gst_treatment or "",
                                "GstOvrdnTypeofsupply":"Goods",
                                "GstHsnName":row.gst_hsn_code if row.gst_hsn_code else "",
                                "GstHsnDescription":frappe.db.get_value("GST HSN Code",row.gst_hsn_code,"description") if frappe.db.get_value("GST HSN Code",row.gst_hsn_code,"description") else "",
                                "CgstGstRateDutyhead":"CGST",
                                "CgstGstRateValuationtype":"Based on Value",
                                "CgstGstRate":str(row.igst_rate/2) if row.igst_rate>0 else "",
                                "SgstGstRateDutyhead":"SGST/UTGST",
                                "SgstGstRateValuationtype":"Based on Value",
                                "SgstGstRate":str(row.igst_rate/2) if row.igst_rate>0 else "",
                                "IgstGstRateDutyhead":"IGST",
                                "IgstGstRateValuationtype":"Based on Value",
                                "IgstGstRate":str(row.igst_rate) if row.igst_rate>0 else "",
                                "Reference": document.bill_no if document.bill_no else "",
                                "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                                "VoucherSourceGodown": "",				
                                "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                            }
                            list_of_purchase_invoices.append(doc_json)

                        elif 'Input GST In-state' in document.taxes_and_charges:
                            doc_json ={
                                "Autoid": "",
                                "CompanyNumber": str(company_idx),
                                "TallyMasterid": 1,
                                "Voucherid": document.name,
                                "VoucherNumber": document.name,
                                "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                                "VoucherType": "Debit Note",
                                "VoucherTypeParent": "Debit Note",
                                "LedgerName": row.item_name.upper() +" PURCHASE" if row.item_name else "PURCHASE",
                                "LedgerParent": "Purchase Accounts",
                                "LedgerAddress":"",
                                "LedgerState": "",
                                "LedgerCountry": "",
                                "LedgerPincode": "",
                                "LedgerMobile": "",
                                "LedgerGstReg": "",
                                "LedgerPan": "",
                                "LedgerGstin": "",
                                "BillName": "",
                                "BillDate": "",
                                "CrDr": "Cr",
                                "CostCategory": "",
                                "CostCentre": (cost_center.company) if cost_center else "",
                                "Stockitem": "",
                                "Godown": "",
                                "BatchNo": "",
                                "Quantity": "",
                                "Rate": "",
                                "Discount": "",
                                "Amount": str(abs(row.net_amount)) if row.net_amount else "",
                                "OrderNo": "",
                                "OrderDate": "",
                                "TrackingNo": "",
                                "TrackingDate": "",
                                "TermsOfPayment": "",
                                "OtherRef": "",
                                "TermsOfDelivery1": "",
                                "TermsOfDelivery2": "",
                                "DispatchDocNo": "",
                                "ReceiptDocNo": "",
                                "DispatchedThrough": "",
                                "Destination": "",
                                "CarrierName": "",
                                "BillOfLanding": "",
                                "BillOfLandingDate": "",
                                "VehicleNo": "",
                            # Commented for future need
                                # "BuyerName": supplier.supplier_name,
                                # "BuyerMailingName": supplier.supplier_name,
                                # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                                # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                                # "BuyerState": supplier_add.state if supplier_add.state else "",
                                # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                                # "BuyerGstReg": gst_category if gst_category else "",
                                # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                                # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                                # "ConsigneeName": supplier.supplier_name,
                                # "ConsigneeMailingName": supplier.supplier_name,
                                # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                                # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                                # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                                # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                                # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                                # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                                # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                            # Commented for future need
                                "BuyerName": "",
                                "BuyerMailingName": "",
                                "BuyerAddress1": "",
                                "BuyerAddress2": "",
                                "BuyerState": "",
                                "BuyerCountry": "",
                                "BuyerGstReg": "",
                                "BuyerGSTIN": "",
                                "BuyerPincode": "",
                                "ConsigneeName": "",
                                "ConsigneeMailingName": "",
                                "ConsigneeAddress1": "",
                                "ConsigneeAddress2": "",
                                "ConsigneeState": "",
                                "ConsigneeCountry": "",
                                "ConsigneeGSTIN": "",
                                "ConsigneePincode": "",
                                "PlaceOfSupply": "",
                                "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                                "CmpGstin": company.gstin if company.gstin else "",
                                "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                                "GstOvrdnTaxability": "Exempt" if row.gst_treatment == "Exempted" or row.gst_treatment == "Non-GST" or row.gst_treatment == "Nil-Rated" else row.gst_treatment or "",
                                "GstOvrdnTypeofsupply":"Goods",
                                "GstHsnName":row.gst_hsn_code if row.gst_hsn_code else "",
                                "GstHsnDescription":frappe.db.get_value("GST HSN Code",row.gst_hsn_code,"description") if frappe.db.get_value("GST HSN Code",row.gst_hsn_code,"description") else "",
                                "CgstGstRateDutyhead":"CGST",
                                "CgstGstRateValuationtype":"Based on Value",
                                "CgstGstRate":str(row.cgst_rate) if row.cgst_rate>0 else "",
                                "SgstGstRateDutyhead":"SGST/UTGST",
                                "SgstGstRateValuationtype":"Based on Value",
                                "SgstGstRate":str(row.sgst_rate) if row.sgst_rate>0 else "",
                                "IgstGstRateDutyhead":"IGST",
                                "IgstGstRateValuationtype":"Based on Value",
                                "IgstGstRate":str(row.cgst_rate+row.sgst_rate) if row.cgst_rate>0 and row.sgst_rate>0 else "",
                                "Reference": document.bill_no if document.bill_no else "",
                                "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                                "VoucherSourceGodown": "",				
                                "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                            }
                            list_of_purchase_invoices.append(doc_json)

                        else:
                            doc_json ={
                                "Autoid": "",
                                "CompanyNumber": str(company_idx),
                                "TallyMasterid": 1,
                                "Voucherid": document.name,
                                "VoucherNumber": document.name,
                                "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                                "VoucherType": "Debit Note",
                                "VoucherTypeParent": "Debit Note",
                                "LedgerName": row.item_name.upper() +" PURCHASE" if row.item_name else "PURCHASE",
                                "LedgerParent": "Purchase Accounts",
                                "LedgerAddress":"",
                                "LedgerState": "",
                                "LedgerCountry": "",
                                "LedgerPincode": "",
                                "LedgerMobile": "",
                                "LedgerGstReg": "",
                                "LedgerPan": "",
                                "LedgerGstin": "",
                                "BillName": "",
                                "BillDate": "",
                                "CrDr": "Cr",
                                "CostCategory": "",
                                "CostCentre": (cost_center.company) if cost_center else "",
                                "Stockitem": "",
                                "Godown": "",
                                "BatchNo": "",
                                "Quantity": "",
                                "Rate": "",
                                "Discount": "",
                                "Amount": str(abs(row.net_amount)) if row.net_amount else "",
                                "OrderNo": "",
                                "OrderDate": "",
                                "TrackingNo": "",
                                "TrackingDate": "",
                                "TermsOfPayment": "",
                                "OtherRef": "",
                                "TermsOfDelivery1": "",
                                "TermsOfDelivery2": "",
                                "DispatchDocNo": "",
                                "ReceiptDocNo": "",
                                "DispatchedThrough": "",
                                "Destination": "",
                                "CarrierName": "",
                                "BillOfLanding": "",
                                "BillOfLandingDate": "",
                                "VehicleNo": "",
                            # Commented for future need
                                # "BuyerName": supplier.supplier_name,
                                # "BuyerMailingName": supplier.supplier_name,
                                # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                                # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                                # "BuyerState": supplier_add.state if supplier_add.state else "",
                                # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                                # "BuyerGstReg": gst_category if gst_category else "",
                                # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                                # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                                # "ConsigneeName": supplier.supplier_name,
                                # "ConsigneeMailingName": supplier.supplier_name,
                                # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                                # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                                # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                                # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                                # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                                # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                                # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                            # Commented for future need
                                "BuyerName": "",
                                "BuyerMailingName": "",
                                "BuyerAddress1": "",
                                "BuyerAddress2": "",
                                "BuyerState": "",
                                "BuyerCountry": "",
                                "BuyerGstReg": "",
                                "BuyerGSTIN": "",
                                "BuyerPincode": "",
                                "ConsigneeName": "",
                                "ConsigneeMailingName": "",
                                "ConsigneeAddress1": "",
                                "ConsigneeAddress2": "",
                                "ConsigneeState": "",
                                "ConsigneeCountry": "",
                                "ConsigneeGSTIN": "",
                                "ConsigneePincode": "",
                                "PlaceOfSupply": "",
                                "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                                "CmpGstin": company.gstin if company.gstin else "",
                                "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                                "GstOvrdnTaxability": "Exempt" if row.gst_treatment == "Exempted" or row.gst_treatment == "Non-GST" or row.gst_treatment == "Nil-Rated" else row.gst_treatment or "",
                                "GstOvrdnTypeofsupply":"Goods",
                                "GstHsnName":row.gst_hsn_code if row.gst_hsn_code else "",
                                "GstHsnDescription":frappe.db.get_value("GST HSN Code",row.gst_hsn_code,"description") if frappe.db.get_value("GST HSN Code",row.gst_hsn_code,"description") else "",
                                "CgstGstRateDutyhead":"CGST",
                                "CgstGstRateValuationtype":"Based on Value",
                                "CgstGstRate":"",
                                "SgstGstRateDutyhead":"SGST/UTGST",
                                "SgstGstRateValuationtype":"Based on Value",
                                "SgstGstRate":"",
                                "IgstGstRateDutyhead":"IGST",
                                "IgstGstRateValuationtype":"Based on Value",
                                "IgstGstRate":"",
                                "Reference": document.bill_no if document.bill_no else "",
                                "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                                "VoucherSourceGodown": "",				
                                "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                            }
                            list_of_purchase_invoices.append(doc_json)

            else:
                parrent_acc = frappe.get_doc("Account", key)
                doc_json ={
                    "Autoid": "",
                    "CompanyNumber": str(company_idx),
                    "TallyMasterid": 1,
                    "Voucherid": document.name,
                    "VoucherNumber": document.name,
                    "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                    "VoucherType": "Debit Note",
                    "VoucherTypeParent": "Debit Note",
                    "LedgerName": "Roundoff"  if "Rounded Off" in key else (key).split(" - ")[0],
                    "LedgerParent": "Duties & Taxes" if parrent_acc.account_type == "Tax" or "Tax Assets" in parrent_acc.parent_account  else (parrent_acc.parent_account).split(" - ")[0],
                    "LedgerAddress":"",
                    "LedgerState": "",
                    "LedgerCountry": "",
                    "LedgerPincode": "",
                    "LedgerMobile": "",
                    "LedgerGstReg": "",
                    "LedgerPan": "",
                    "LedgerGstin": "",
                    "BillName": "",
                    "BillDate": "",
                    "CrDr":"Cr",
                    "CostCategory": "",
                    "CostCentre": (cost_center.company) if cost_center else "",
                    "Stockitem": "",
                    "Godown": "",
                    "BatchNo": "",
                    "Quantity": "",
                    "Rate": "",
                    "Discount": "",
                    "Amount": str(value['credit']),
                    "OrderNo": "",
                    "OrderDate": "",
                    "TrackingNo": "",
                    "TrackingDate": "",
                    "TermsOfPayment": "",
                    "OtherRef": "",
                    "TermsOfDelivery1": "",
                    "TermsOfDelivery2": "",
                    "DispatchDocNo": "",
                    "ReceiptDocNo": "",
                    "DispatchedThrough": "",
                    "Destination": "",
                    "CarrierName": "",
                    "BillOfLanding": "",
                    "BillOfLandingDate": "",
                    "VehicleNo": "",
                # Commented for future need
                    # "BuyerName": supplier.supplier_name,
                    # "BuyerMailingName": supplier.supplier_name,
                    # "BuyerAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                    # "BuyerAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                    # "BuyerState": supplier_add.state if supplier_add.state else "",
                    # "BuyerCountry": supplier_add.country if supplier_add.country else "",
                    # "BuyerGstReg": gst_category if gst_category else "",
                    # "BuyerGSTIN": supplier.gstin if supplier.gstin else "",
                    # "BuyerPincode": supplier_add.pincode if supplier_add.pincode else "",
                    # "ConsigneeName": supplier.supplier_name,
                    # "ConsigneeMailingName": supplier.supplier_name,
                    # "ConsigneeAddress1": supplier_add.address_line1 if supplier_add.address_line1 else "",
                    # "ConsigneeAddress2": supplier_add.address_line2 if supplier_add.address_line2 else "",
                    # "ConsigneeState": supplier_add.state if supplier_add.state else "",
                    # "ConsigneeCountry": supplier_add.country if supplier_add.country else "",
                    # "ConsigneeGSTIN": supplier.gstin if supplier.gstin else "",
                    # "ConsigneePincode": supplier_add.pincode if supplier_add.pincode else "",
                    # "PlaceOfSupply": (document.place_of_supply).split("-")[1] if document.place_of_supply else "",
                # Commented for future need
                    "BuyerName": "",
                    "BuyerMailingName": "",
                    "BuyerAddress1": "",
                    "BuyerAddress2": "",
                    "BuyerState": "",
                    "BuyerCountry": "",
                    "BuyerGstReg": "",
                    "BuyerGSTIN": "",
                    "BuyerPincode": "",
                    "ConsigneeName": "",
                    "ConsigneeMailingName": "",
                    "ConsigneeAddress1": "",
                    "ConsigneeAddress2": "",
                    "ConsigneeState": "",
                    "ConsigneeCountry": "",
                    "ConsigneeGSTIN": "",
                    "ConsigneePincode": "",
                    "PlaceOfSupply": "",
                    "CmpGstRegistrationType":gst_category_company if gst_category_company else "",
                    "CmpGstin": company.gstin if company.gstin else "",
                    "CmpGstState": company_address_billing.state if company_address_billing.state else "",
                    "GstOvrdnTaxability":"",
                    "GstOvrdnTypeofsupply":"",
                    "GstHsnName":"",
                    "GstHsnDescription":"",
                    "CgstGstRateDutyhead":"",
                    "CgstGstRateValuationtype":"",
                    "CgstGstRate":"",
                    "SgstGstRateDutyhead":"",
                    "SgstGstRateValuationtype":"",
                    "SgstGstRate":"",
                    "IgstGstRateDutyhead":"",
                    "IgstGstRateValuationtype":"",
                    "IgstGstRate":"",
                    "Reference": document.bill_no if document.bill_no else "",
                    "ReferenceDate": datetime.strptime(str(document.bill_date),'%Y-%m-%d').strftime('%d-%m-%Y') if document.bill_date else "",
                    "VoucherSourceGodown": "",				
                    "Narration": (document.remarks).replace("\n",". ") if document.remarks else ""
                }
                list_of_purchase_invoices.append(doc_json)
  
    response_purchase = {
            "status": True,
            "VOUCHERDETAILS": {
                "VOUCHER": list_of_purchase_invoices
            }
        }
    
    # print(json.dumps(response_purchase))
    return response_purchase
def get_company_address(company_name):
   
    linked_address = frappe.get_all("Address", filters={"link_doctype": "Company", "link_name": company_name}, pluck="name")
    return linked_address