import frappe
import json
import requests
from datetime import datetime

@frappe.whitelist(allow_guest=True)
def get_purchase_invoice():

    doc_list = frappe.get_all('Purchase Invoice', filters={'docstatus': 1, "update_stock":0, 'is_return': 0}, fields=['*'])
    list_of_purchases= []
    for doc in doc_list:
        supplier = frappe.get_doc("Supplier", doc.supplier)
        supplier_add = frappe.get_doc("Address",supplier.supplier_primary_address)
        list_of_purchases.append(purchase_invoice_json(get_tagged_accounts_amount(doc.name), supplier, supplier_add, doc))
    return list_of_purchases

def get_tagged_accounts_amount(purchase_invoice_name):

    purchase_invoice = frappe.get_doc("Purchase Invoice", purchase_invoice_name)
    account_amount = {}
    gl_entries = frappe.get_all("GL Entry", filters={"voucher_type": "Purchase Invoice", "voucher_no": purchase_invoice_name}, fields=["*"], order_by="creation asc")
    for entry in gl_entries:
        account = entry.account
        if entry.debit is not None and entry.debit > 0:
            if account in account_amount:
                account_amount[account]['debit'] += entry.debit
            else:
                account_amount[account] = {'debit': entry.debit, 'credit': 0}

        elif entry.credit is not None and entry.credit > 0:
            if account in account_amount:
                account_amount[account]['credit'] += entry.credit
            else:
                account_amount[account] = {'debit': 0, 'credit': entry.credit}
    return (account_amount)

def purchase_invoice_json(tagged_acc, supplier, supplier_add, doc):

    supplier = supplier
    supplier_add = supplier_add
    document = frappe.get_doc("Purchase Invoice", doc.name)
    company = frappe.get_doc("Company", doc.company)
    company_address_billing = frappe.get_doc("Address", get_company_address(doc.company)[0]) if document.billing_address else ""
    company_address_shipping = frappe.get_doc("Address", get_company_address(doc.company)[0]) if document.shipping_address else ""
     
    gst_category = {
        "Unregistered": "Unregistered/Vendor",
        "Registered Regular": "Regular",
        "Registered Composition": "Composition",
        "SEZ": "Regular - SEZ"
    }.get(supplier.gst_category, supplier.gst_category)

    gst_category_billing = {
        "Unregistered": "Unregistered/Consumer",
        "Registered Regular": "Regular",
        "Registered Composition": "Composition",
        "SEZ": "Regular - SEZ"
    }.get(company_address_billing.gst_category, company_address_billing.gst_category)

    gst_category_shipping = {
        "Unregistered": "Unregistered/Consumer",
        "Registered Regular": "Regular",
        "Registered Composition": "Composition",
        "SEZ": "Regular - SEZ"
    }.get(company_address_shipping.gst_category, company_address_shipping.gst_category)

    list_of_purchase_invoices = []
    
    for key, value in tagged_acc.items():
        if value['credit'] > 0:
            if "Creditors" in key:
                doc_json = {
                        "Autoid": "",
                        "CompanyNumber": company.name,
                        "TallyMasterid": 1,
                        "Voucherid": document.name,
                        "VoucherNumber": document.name,
                        "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherType": "Purchase",
                        "VoucherTypeParent": "Purchase",
                        "LedgerName": supplier.supplier_name,
                        "LedgerParent": "Sundry Creditors",
                        "LedgerAddress": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "LedgerState": supplier_add.state if supplier_add.state else "",
                        "LedgerCountry": supplier_add.country if supplier_add.country else "",
                        "LedgerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        "LedgerMobile": supplier.mobile_no if supplier.mobile_no else "",
                        "LedgerGstReg": gst_category if gst_category else "",
                        "LedgerPan": supplier.pan if supplier.pan else "",
                        "LedgerGstin": supplier.gstin if supplier.gstin else "",
                        "BillName": "",
                        "BillDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "CrDr": "Cr",
                        "CostCategory": "",
                        "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                        "Stockitem": "",
                        "Godown": "",
                        "BatchNo": "",
                        "Quantity": "",
                        "Rate": "",
                        "Discount": "",
                        "Amount": str(value['credit']),
                        "OrderNo": "",
                        "OrderDate": "",
                        "TrackingNo": "",
                        "TrackingDate": "",
                        "TermsOfPayment": "",
                        "OtherRef": "",
                        "TermsOfDelivery1": "",
                        "TermsOfDelivery2": "",
                        "DispatchDocNo": "",
                        "ReceiptDocNo": "",
                        "DispatchedThrough": "",
                        "Destination": "",
                        "CarrierName": "",
                        "BillOfLanding": "",
                        "BillOfLandingDate": "",
                        "VehicleNo": "",
                        "BuyerName": company.name,
                        "BuyerMailingName": company.name,
                        "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                        "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                        "BuyerState": company_address_billing.state if company_address_billing.state else "",
                        "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                        "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                        "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                        "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                        "ConsigneeName": company.name,
                        "ConsigneeMailingName": company.name,
                        "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                        "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                        "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                        "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                        "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                        "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                        "PlaceOfSupply": "",
                        "CmpGstRegistrationType":gst_category if gst_category else "",
                        "CmpGstin": supplier.gstin if supplier.gstin else "",
                        "CmpGstState": supplier_add.state if supplier_add.state else "",
                        "GstOvrdnTaxability":"",
                        "GstOvrdnTypeofsupply":"",
                        "GstHsnName":"",
                        "GstHsnDescription":"",
                        "CgstGstRateDutyhead":"",
                        "CgstGstRateValuationtype":"",
                        "CgstGstRate":"",
                        "SgstGstRateDutyhead":"",
                        "SgstGstRateValuationtype":"",
                        "SgstGstRate":"",
                        "IgstGstRateDutyhead":"",
                        "IgstGstRateValuationtype":"",
                        "IgstGstRate":"",
                        "Reference": "",
                        "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherSourceGodown": "",				
                        "Narration": document.remarks if document.remarks else "",
                    }
                list_of_purchase_invoices.append(doc_json)
            else:
                parrent_acc = frappe.get_doc("Account", key)
                doc_json = {
                        "Autoid": "",
                        "CompanyNumber": company.name,
                        "TallyMasterid": 1,
                        "Voucherid": document.name,
                        "VoucherNumber": document.name,
                        "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherType": "Purchase",
                        "VoucherTypeParent": "Purchase",
                        "LedgerName": (key).split(" - ")[0],
                        "LedgerParent": (parrent_acc.parent_account).split(" - ")[0] if parrent_acc.parent_account else "",
                        "LedgerAddress":"",
                        "LedgerState": "",
                        "LedgerCountry": "",
                        "LedgerPincode": "",
                        "LedgerMobile": "",
                        "LedgerGstReg": "",
                        "LedgerPan": "",
                        "LedgerGstin": "",
                        "BillName": "",
                        "BillDate": "",
                        "CrDr": "Cr",
                        "CostCategory": "",
                        "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                        "Stockitem": "",
                        "Godown": "",
                        "BatchNo": "",
                        "Quantity": "",
                        "Rate": "",
                        "Discount": "",
                        "Amount": str(value['credit']),
                        "OrderNo": "",
                        "OrderDate": "",
                        "TrackingNo": "",
                        "TrackingDate": "",
                        "TermsOfPayment": "",
                        "OtherRef": "",
                        "TermsOfDelivery1": "",
                        "TermsOfDelivery2": "",
                        "DispatchDocNo": "",
                        "ReceiptDocNo": "",
                        "DispatchedThrough": "",
                        "Destination": "",
                        "CarrierName": "",
                        "BillOfLanding": "",
                        "BillOfLandingDate": "",
                        "VehicleNo": "",
                        "BuyerName": company.name,
                        "BuyerMailingName": company.name,
                        "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                        "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                        "BuyerState": company_address_billing.state if company_address_billing.state else "",
                        "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                        "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                        "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                        "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                        "ConsigneeName": company.name,
                        "ConsigneeMailingName": company.name,
                        "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                        "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                        "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                        "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                        "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                        "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                        "PlaceOfSupply": "",
                        "CmpGstRegistrationType":gst_category if gst_category else "",
                        "CmpGstin": supplier.gstin if supplier.gstin else "",
                        "CmpGstState": supplier_add.state if supplier_add.state else "",
                        "GstOvrdnTaxability":"",
                        "GstOvrdnTypeofsupply":"",
                        "GstHsnName":"",
                        "GstHsnDescription":"",
                        "CgstGstRateDutyhead":"",
                        "CgstGstRateValuationtype":"",
                        "CgstGstRate":"",
                        "SgstGstRateDutyhead":"",
                        "SgstGstRateValuationtype":"",
                        "SgstGstRate":"",
                        "IgstGstRateDutyhead":"",
                        "IgstGstRateValuationtype":"",
                        "IgstGstRate":"",
                        "Reference": "",
                        "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherSourceGodown": "",				
                        "Narration": document.remarks if document.remarks else ""
                    }
                list_of_purchase_invoices.append(doc_json)

        elif value['debit'] > 0:
            if 'Creditors' in key:
                doc_json = {
                        "Autoid": "",
                        "CompanyNumber": company.name,
                        "TallyMasterid": 1,
                        "Voucherid": document.name,
                        "VoucherNumber": document.name,
                        "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherType": "Purchase",
                        "VoucherTypeParent": "Purchase",
                        "LedgerName": supplier.supplier_name,
                        "LedgerParent": "Sundry Creditors",
                        "LedgerAddress": supplier_add.address_line1 if supplier_add.address_line1 else "",
                        "LedgerState": supplier_add.state if supplier_add.state else "",
                        "LedgerCountry": supplier_add.country if supplier_add.country else "",
                        "LedgerPincode": supplier_add.pincode if supplier_add.pincode else "",
                        "LedgerMobile": supplier.mobile_no if supplier.mobile_no else "",
                        "LedgerGstReg": gst_category if gst_category else "",
                        "LedgerPan": supplier.pan if supplier.pan else "",
                        "LedgerGstin": supplier.gstin if supplier.gstin else "",
                        "BillName": "",
                        "BillDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "CrDr": "Dr",
                        "CostCategory": "",
                        "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                        "Stockitem": "",
                        "Godown": "",
                        "BatchNo": "",
                        "Quantity": "",
                        "Rate": "",
                        "Discount": "",
                        "Amount": str(value['debit']),
                        "OrderNo": "",
                        "OrderDate": "",
                        "TrackingNo": "",
                        "TrackingDate": "",
                        "TermsOfPayment": "",
                        "OtherRef": "",
                        "TermsOfDelivery1": "",
                        "TermsOfDelivery2": "",
                        "DispatchDocNo": "",
                        "ReceiptDocNo": "",
                        "DispatchedThrough": "",
                        "Destination": "",
                        "CarrierName": "",
                        "BillOfLanding": "",
                        "BillOfLandingDate": "",
                        "VehicleNo": "",
                        "BuyerName": company.name,
                        "BuyerMailingName": company.name,
                        "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                        "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                        "BuyerState": company_address_billing.state if company_address_billing.state else "",
                        "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                        "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                        "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                        "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                        "ConsigneeName": company.name,
                        "ConsigneeMailingName": company.name,
                        "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                        "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                        "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                        "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                        "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                        "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                        "PlaceOfSupply": "",
                        "CmpGstRegistrationType":gst_category if gst_category else "",
                        "CmpGstin": supplier.gstin if supplier.gstin else "",
                        "CmpGstState": supplier_add.state if supplier_add.state else "",
                        "GstOvrdnTaxability":"",
                        "GstOvrdnTypeofsupply":"",
                        "GstHsnName":"",
                        "GstHsnDescription":"",
                        "CgstGstRateDutyhead":"",
                        "CgstGstRateValuationtype":"",
                        "CgstGstRate":"",
                        "SgstGstRateDutyhead":"",
                        "SgstGstRateValuationtype":"",
                        "SgstGstRate":"",
                        "IgstGstRateDutyhead":"",
                        "IgstGstRateValuationtype":"",
                        "IgstGstRate":"",
                        "Reference": "",
                        "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                        "VoucherSourceGodown": "",				
                        "Narration": document.remarks if document.remarks else "",
                    }
                list_of_purchase_invoices.append(doc_json)
            elif "Stock Received But Not Billed" in key:
                parrent_acc = frappe.get_doc("Account", key)
                if 'Input GST Out-state' in document.taxes_and_charges:
                        doc_json ={
                            "Autoid": "",
                            "CompanyNumber": company.name,
                            "TallyMasterid": 1,
                            "Voucherid": document.name,
                            "VoucherNumber": document.name,
                            "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherType": "Purchase",
                            "VoucherTypeParent": "Purchase",
                            "LedgerName": (key).split(" - ")[0],
                            "LedgerParent": (parrent_acc.parent_account).split(" - ")[0] if parrent_acc.parent_account else "",
                            "LedgerAddress":"",
                            "LedgerState": "",
                            "LedgerCountry": "",
                            "LedgerPincode": "",
                            "LedgerMobile": "",
                            "LedgerGstReg": "",
                            "LedgerPan": "",
                            "LedgerGstin": "",
                            "BillName": "",
                            "BillDate": "",
                            "CrDr": "Dr",
                            "CostCategory": "",
                            "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                            "Stockitem": "",
                            "Godown": "",
                            "BatchNo": "",
                            "Quantity": "",
                            "Rate": "",
                            "Discount": "",
                            "Amount": str(value['debit']),
                            "OrderNo": "",
                            "OrderDate": "",
                            "TrackingNo": "",
                            "TrackingDate": "",
                            "TermsOfPayment": "",
                            "OtherRef": "",
                            "TermsOfDelivery1": "",
                            "TermsOfDelivery2": "",
                            "DispatchDocNo": "",
                            "ReceiptDocNo": "",
                            "DispatchedThrough": "",
                            "Destination": "",
                            "CarrierName": "",
                            "BillOfLanding": "",
                            "BillOfLandingDate": "",
                            "VehicleNo": "",
                            "BuyerName": company.name,
                            "BuyerMailingName": company.name,
                            "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                            "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                            "BuyerState": company_address_billing.state if company_address_billing.state else "",
                            "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                            "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                            "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                            "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                            "ConsigneeName": company.name,
                            "ConsigneeMailingName": company.name,
                            "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                            "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                            "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                            "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                            "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                            "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                            "PlaceOfSupply": "",
                            "CmpGstRegistrationType":gst_category if gst_category else "",
                            "CmpGstin": supplier.gstin if supplier.gstin else "",
                            "CmpGstState": supplier_add.state if supplier_add.state else "",
                            "GstOvrdnTaxability":"",
                            "GstOvrdnTypeofsupply":"",
                            "GstHsnName":"",
                            "GstHsnDescription":"",
                            "CgstGstRateDutyhead":"CGST",
                            "CgstGstRateValuationtype":"",
                            "CgstGstRate":str(document.taxes[0].rate/2) if document.taxes[0].rate else "",
                            "SgstGstRateDutyhead":"SGST",
                            "SgstGstRateValuationtype":"",
                            "SgstGstRate":str(document.taxes[0].rate/2) if document.taxes[0].rate else "",
                            "IgstGstRateDutyhead":"IGST",
                            "IgstGstRateValuationtype":"",
                            "IgstGstRate":str(document.taxes[0].rate) if document.taxes[0].rate else "",
                            "Reference": "",
                            "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherSourceGodown": "",				
                            "Narration": document.remarks if document.remarks else ""
                        }
                        list_of_purchase_invoices.append(doc_json)

                elif 'Input GST In-state' in document.taxes_and_charges:
                        doc_json ={
                            "Autoid": "",
                            "CompanyNumber": company.name,
                            "TallyMasterid": 1,
                            "Voucherid": document.name,
                            "VoucherNumber": document.name,
                            "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherType": "Purchase",
                            "VoucherTypeParent": "Purchase",
                            "LedgerName": (key).split(" - ")[0],
                            "LedgerParent": (parrent_acc.parent_account).split(" - ")[0] if parrent_acc.parent_account else "",
                            "LedgerAddress":"",
                            "LedgerState": "",
                            "LedgerCountry": "",
                            "LedgerPincode": "",
                            "LedgerMobile": "",
                            "LedgerGstReg": "",
                            "LedgerPan": "",
                            "LedgerGstin": "",
                            "BillName": "",
                            "BillDate": "",
                            "CrDr": "Dr",
                            "CostCategory": "",
                            "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                            "Stockitem": "",
                            "Godown": "",
                            "BatchNo": "",
                            "Quantity": "",
                            "Rate": "",
                            "Discount": "",
                            "Amount": str(value['debit']),
                            "OrderNo": "",
                            "OrderDate": "",
                            "TrackingNo": "",
                            "TrackingDate": "",
                            "TermsOfPayment": "",
                            "OtherRef": "",
                            "TermsOfDelivery1": "",
                            "TermsOfDelivery2": "",
                            "DispatchDocNo": "",
                            "ReceiptDocNo": "",
                            "DispatchedThrough": "",
                            "Destination": "",
                            "CarrierName": "",
                            "BillOfLanding": "",
                            "BillOfLandingDate": "",
                            "VehicleNo": "",
                            "BuyerName": company.name,
                            "BuyerMailingName": company.name,
                            "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                            "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                            "BuyerState": company_address_billing.state if company_address_billing.state else "",
                            "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                            "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                            "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                            "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                            "ConsigneeName": company.name,
                            "ConsigneeMailingName": company.name,
                            "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                            "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                            "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                            "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                            "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                            "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                            "PlaceOfSupply": "",
                            "CmpGstRegistrationType":gst_category if gst_category else "",
                            "CmpGstin": supplier.gstin if supplier.gstin else "",
                            "CmpGstState": supplier_add.state if supplier_add.state else "",
                            "GstOvrdnTaxability":"",
                            "GstOvrdnTypeofsupply":"",
                            "GstHsnName":"",
                            "GstHsnDescription":"",
                            "CgstGstRateDutyhead":"CGST",
                            "CgstGstRateValuationtype":"",
                            "CgstGstRate":str(document.taxes[0].rate) if document.taxes[0].rate else "",
                            "SgstGstRateDutyhead":"SGST",
                            "SgstGstRateValuationtype":"",
                            "SgstGstRate":str(document.taxes[1].rate) if document.taxes[1].rate else "",
                            "IgstGstRateDutyhead":"IGST",
                            "IgstGstRateValuationtype":"",
                            "IgstGstRate":str(document.taxes[0].rate + document.taxes[1].rate) if document.taxes[0].rate and document.taxes[1].rate else "",
                            "Reference": "",
                            "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherSourceGodown": "",				
                            "Narration": document.remarks if document.remarks else ""
                        }
                        list_of_purchase_invoices.append(doc_json)

                else:
                        doc_json ={
                            "Autoid": "",
                            "CompanyNumber": company.name,
                            "TallyMasterid": 1,
                            "Voucherid": document.name,
                            "VoucherNumber": document.name,
                            "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherType": "Purchase",
                            "VoucherTypeParent": "Purchase",
                            "LedgerName": (key).split(" - ")[0],
                            "LedgerParent": (parrent_acc.parent_account).split(" - ")[0] if parrent_acc.parent_account else "",
                            "LedgerAddress":"",
                            "LedgerState": "",
                            "LedgerCountry": "",
                            "LedgerPincode": "",
                            "LedgerMobile": "",
                            "LedgerGstReg": "",
                            "LedgerPan": "",
                            "LedgerGstin": "",
                            "BillName": "",
                            "BillDate": "",
                            "CrDr": "Dr",
                            "CostCategory": "",
                            "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                            "Stockitem": "",
                            "Godown": "",
                            "BatchNo": "",
                            "Quantity": "",
                            "Rate": "",
                            "Discount": "",
                            "Amount": str(value['debit']),
                            "OrderNo": "",
                            "OrderDate": "",
                            "TrackingNo": "",
                            "TrackingDate": "",
                            "TermsOfPayment": "",
                            "OtherRef": "",
                            "TermsOfDelivery1": "",
                            "TermsOfDelivery2": "",
                            "DispatchDocNo": "",
                            "ReceiptDocNo": "",
                            "DispatchedThrough": "",
                            "Destination": "",
                            "CarrierName": "",
                            "BillOfLanding": "",
                            "BillOfLandingDate": "",
                            "VehicleNo": "",
                            "BuyerName": company.name,
                            "BuyerMailingName": company.name,
                            "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                            "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                            "BuyerState": company_address_billing.state if company_address_billing.state else "",
                            "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                            "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                            "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                            "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                            "ConsigneeName": company.name,
                            "ConsigneeMailingName": company.name,
                            "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                            "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                            "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                            "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                            "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                            "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                            "PlaceOfSupply": "",
                            "CmpGstRegistrationType":gst_category if gst_category else "",
                            "CmpGstin": supplier.gstin if supplier.gstin else "",
                            "CmpGstState": supplier_add.state if supplier_add.state else "",
                            "GstOvrdnTaxability": "",
                            "GstOvrdnTypeofsupply":"",
                            "GstHsnName":"",
                            "GstHsnDescription":"",
                            "CgstGstRateDutyhead":"CGST",
                            "CgstGstRateValuationtype":"",
                            "CgstGstRate":"",
                            "SgstGstRateDutyhead":"SGST",
                            "SgstGstRateValuationtype":"",
                            "SgstGstRate":"",
                            "IgstGstRateDutyhead":"IGST",
                            "IgstGstRateValuationtype":"",
                            "IgstGstRate":"",
                            "Reference": "",
                            "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                            "VoucherSourceGodown": "",				
                            "Narration": document.remarks if document.remarks else ""
                        }
                        list_of_purchase_invoices.append(doc_json)

            else:
                parrent_acc = frappe.get_doc("Account", key)
                doc_json ={
                    "Autoid": "",
                    "CompanyNumber": company.name,
                    "TallyMasterid": 1,
                    "Voucherid": document.name,
                    "VoucherNumber": document.name,
                    "VoucherDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                    "VoucherType": "Purchase",
                    "VoucherTypeParent": "Purchase",
                    "LedgerName": (key).split(" - ")[0],
                    "LedgerParent": (parrent_acc.parent_account).split(" - ")[0] if parrent_acc.parent_account else "",
                    "LedgerAddress":"",
                    "LedgerState": "",
                    "LedgerCountry": "",
                    "LedgerPincode": "",
                    "LedgerMobile": "",
                    "LedgerGstReg": "",
                    "LedgerPan": "",
                    "LedgerGstin": "",
                    "BillName": "",
                    "BillDate": "",
                    "CrDr": "Dr",
                    "CostCategory": "",
                    "CostCentre": (document.cost_center).split(" - ")[0] if document.cost_center else "",
                    "Stockitem": "",
                    "Godown": "",
                    "BatchNo": "",
                    "Quantity": "",
                    "Rate": "",
                    "Discount": "",
                    "Amount": str(value['debit']),
                    "OrderNo": "",
                    "OrderDate": "",
                    "TrackingNo": "",
                    "TrackingDate": "",
                    "TermsOfPayment": "",
                    "OtherRef": "",
                    "TermsOfDelivery1": "",
                    "TermsOfDelivery2": "",
                    "DispatchDocNo": "",
                    "ReceiptDocNo": "",
                    "DispatchedThrough": "",
                    "Destination": "",
                    "CarrierName": "",
                    "BillOfLanding": "",
                    "BillOfLandingDate": "",
                    "VehicleNo": "",
                    "BuyerName": company.name,
                    "BuyerMailingName": company.name,
                    "BuyerAddress1": company_address_billing.address_line1 if company_address_billing.address_line1 else "",
                    "BuyerAddress2": company_address_billing.address_line2 if company_address_billing.address_line2 else "",
                    "BuyerState": company_address_billing.state if company_address_billing.state else "",
                    "BuyerCountry": company_address_billing.country if company_address_billing.country else "",
                    "BuyerGstReg": gst_category_billing if gst_category_billing else "",
                    "BuyerGSTIN": company_address_billing.gstin if company.gstin else "",
                    "BuyerPincode": company_address_billing.pincode if company_address_billing.pincode else "",
                    "ConsigneeName": company.name,
                    "ConsigneeMailingName": company.name,
                    "ConsigneeAddress1": company_address_shipping.address_line1 if company_address_shipping.address_line1 else "",
                    "ConsigneeAddress2": company_address_shipping.address_line2 if company_address_shipping.address_line2 else "",
                    "ConsigneeState": company_address_shipping.state if company_address_shipping.state else "",
                    "ConsigneeCountry": company_address_shipping.country if company_address_shipping.country else "",
                    "ConsigneeGSTIN": company_address_shipping.gstin if company.gstin else "",
                    "ConsigneePincode": company_address_shipping.pincode if company_address_shipping.pincode else "",
                    "PlaceOfSupply": "",
                    "CmpGstRegistrationType":gst_category if gst_category else "",
                    "CmpGstin": supplier.gstin if supplier.gstin else "",
                    "CmpGstState": supplier_add.state if supplier_add.state else "",
                    "GstOvrdnTaxability":"",
                    "GstOvrdnTypeofsupply":"",
                    "GstHsnName":"",
                    "GstHsnDescription":"",
                    "CgstGstRateDutyhead":"",
                    "CgstGstRateValuationtype":"",
                    "CgstGstRate":"",
                    "SgstGstRateDutyhead":"",
                    "SgstGstRateValuationtype":"",
                    "SgstGstRate":"",
                    "IgstGstRateDutyhead":"",
                    "IgstGstRateValuationtype":"",
                    "IgstGstRate":"",
                    "Reference": "",
                    "ReferenceDate": datetime.strptime(str(document.posting_date),'%Y-%m-%d').strftime('%d-%m-%Y'),
                    "VoucherSourceGodown": "",				
                    "Narration": document.remarks if document.remarks else ""
                }
                list_of_purchase_invoices.append(doc_json)
  
    response_purchase = {
            "status": True,
            "VOUCHERDETAILS": {
                "VOUCHER": list_of_purchase_invoices
            }
        }
    
    # print(json.dumps(response_purchase))
    return response_purchase
def get_company_address(company_name):
   
    linked_address = frappe.get_all("Address", filters={"link_doctype": "Company", "link_name": company_name}, pluck="name")
    return linked_address