{
"url":{
"username":"lmxTallyInt",
"urlpassword":"$2y$10$0FMx8I0pSr.J3xi6oDMVSekMRoAGXiWj/FkgiV0T9hhljvSTlbwDO",
"ledgerurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.party.get_party",
"godownurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.warehouse.get_warehouse",
"stockgroupurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.item_group.get_itemgroup",
"stockitemurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.item.get_item",
"paymenturl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.payment_entry_pay.get_payment_entry",
"journalurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.journal_entry.get_journal",
"contraurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.contra_entry.get_contra",
"receipturl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.payment_entry_receipt.get_payment_entry",
"salesurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.sales_invoice_inventory.get_sales_inv",
"salesfromdate":"2024-04-01",
"salestodate":"2024-08-31",
"salesnoninvurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.sales_invoice_non_inventory.get_sales_non_inv",
"purchaseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.purchase_invoice_inventory.get_purchase_invoice",
"purchasenoninvurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.purchase_invoice_non_inventory.get_purchase_invoice",
"purchasefromdate":"2023-08-01",
"purchasetodate":"2023-08-10",
"dealerpurchaseurl":"",
"debitnoteurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.debit_note_inventory.get_debit_note",
"debitnotefromdate":"2023-10-01",
"debitnotetodate":"2023-10-31",
"debitnotenoninvurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.debit_note_non_inventory.get_debit_note",
"creditnoteurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.credit_note_inventory.credit_note_inv",
"creditnotefromdate":"2023-08-01",
"creditnotetodate":"2023-08-31",
"creditnotenoninvurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.credit_note_non_inventory.credit_note_non_inv",
"branchtransfer":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.stock_journal.get_stock_entry",
"materialinurl":"",
"materialinfromdate":"2023-10-01",
"materialintodate":"2023-10-31",
"materialouturl":"",
"materialoutfromdate":"2023-10-01",
"materialouttodate":"2023-10-31",
"deliverynoteurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.delivery_note.get_delivery_note",
"deliverynotefromdate":"2023-10-01",
"deliverynotetodate":"2023-10-31",
"receiptnoteurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.purchase_receipt.get_purchsase_receipt",
"receiptnotefromdate":"2023-10-01",
"receiptnotetodate":"2023-10-31",
"ledgerresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.party.fetch_response",
"godownresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.warehouse.fetch_response",
"stockgroupresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.item_group.fetch_response",
"stockitemresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.item.fetch_response",
"responseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.sales_invoice_inventory.fetch_response",
"salesnoninvresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.sales_invoice_non_inventory.fetch_response",
"purchaseresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.purchase_invoice_inventory.fetch_response",
"purchasenoninvresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.purchase_invoice_non_inventory.fetch_response",
"receiptresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.payment_entry_receipt.fetch_response",
"paymentresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.payment_entry_pay.fetch_response",
"journalresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.journal_entry.fetch_response",
"contraresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.contra_entry.fetch_response",
"creditnoteresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.credit_note_inventory.fetch_response",
"creditnotenoninvresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.credit_note_non_inventory.fetch_response",
"debitnoteresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.debit_note_inventory.fetch_response",
"debitnotenoninvresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.debit_note_non_inventory.fetch_response",
"stockjournalresponseurl":"",
"branchtransferresponseurl":"http://106.51.153.24:42015/api/method/ts_tally_integration.tally_integration.utils.api.stock_journal.fetch_response",
"materialinresponseurl":"",
"materialoutresponseurl":"",
"deliverynoteresponseurl":"",
"receiptnoteresponseurl":"",
"token":"68228e21d43f0b0:b9943a5d40f0d6b",
"company1":"THIRVUSOFT PVT LTD",
"company2":"V&Co2",
"company3":"V&Co3",
"company4":"V&Co4",
"company5":"V&Co5",
"company6":"V&Co6",
"company7":"V&Co7",
"company8":"V&Co8",
"company9":"V&Co9",
"company10":"V&Co10",
"company1sundrydebtors":"Sundry Debtors",
"company1sundrycreditors":"Sundry Creditors",
"company1salesaccounts":"Sales Accounts",
"company1purchaseaccounts":"Purchase Accounts",
"company2sundrydebtors":"Sundry Debtors",
"company2sundrycreditors":"Sundry Creditors",
"company2salesaccounts":"Sales Accounts",
"company2purchaseaccounts":"Purchase Accounts",
"company3sundrydebtors":"Sundry Debtors",
"company3sundrycreditors":"Sundry Creditors",
"company3salesaccounts":"Sales Accounts",
"company3purchaseaccounts":"Purchase Accounts",
"company4sundrydebtors":"Trade Debtors",
"company4sundrycreditors":"Sundry Creditors",
"company4salesaccounts":"Sales Accounts",
"company4purchaseaccounts":"Purchase Accounts",
"company5sundrydebtors":"Sundry Debtors",
"company5sundrycreditors":"Sundry Creditors",
"company5salesaccounts":"Sales Accounts",
"company5purchaseaccounts":"Purchase Accounts",
"company6sundrydebtors":"Sundry Debtors",
"company6sundrycreditors":"Sundry Creditors",
"company6salesaccounts":"Sales Accounts",
"company6purchaseaccounts":"Purchase Accounts",
"company7sundrydebtors":"Sundry Debtors",
"company7sundrycreditors":"Sundry Creditors",
"company7salesaccounts":"Sales Accounts",
"company7purchaseaccounts":"Purchase Accounts",
"company8sundrydebtors":"Sundry Debtors",
"company8sundrycreditors":"Sundry Creditors",
"company8salesaccounts":"Sales Accounts",
"company8purchaseaccounts":"Purchase Accounts",
"company9sundrydebtors":"Sundry Debtors",
"company9sundrycreditors":"Sundry Creditors",
"company9salesaccounts":"Sales Accounts",
"company9purchaseaccounts":"Purchase Accounts",
"company10sundrydebtors":"Sundry Debtors",
"company10sundrycreditors":"Sundry Creditors",
"company10salesaccounts":"Sales Accounts",
"company10purchaseaccounts":"Purchase Accounts"
}
}